name: Ft Api Secret Update

on:
  schedule:
    - cron: '30 19 * * *'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  Update-Ft-Api-Secret:
    name: Update Ft Api Secret
    runs-on: ubuntu-22.04

    env:
      CRAWLER_GITHUB_AUTH: ${{ secrets.CRAWLER_GITHUB_AUTH }}
      READ_PRIVATE_SUBMODULE_TOKEN: ${{ secrets.READ_PRIVATE_SUBMODULE_TOKEN }}

      FT_USERNAME: ${{ secrets.FT_USERNAME }}
      FT_PASSWORD: ${{ secrets.FT_PASSWORD }}

      WORKING_DIRECTORY: ${{ vars.WORKING_DIRECTORY }}

    # todo: node 20 으로 업데이트 후 node 설치 부분 지워도 됨.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: true
          token: ${{ env.READ_PRIVATE_SUBMODULE_TOKEN }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build
        run: |
          pnpm i
          pnpm build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run update
        run: |
          pnpm start:updateFtClientSecret
        working-directory: ${{ env.WORKING_DIRECTORY }}
